"""Add categories, brands, sizes, and product_variants tables

Revision ID: c3ea86279162
Revises: 
Create Date: 2026-01-29 14:47:07.396050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3ea86279162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sizes_name'), ['name'], unique=True)

    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sku_suffix', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size_id', name='unique_product_size')
    )
    op.drop_table('inventory')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_products_barcode')
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('barcode')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('sale_items_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_stock_movements_product_id')
        batch_op.create_index(batch_op.f('ix_stock_movements_variant_id'), ['variant_id'], unique=False)
        batch_op.drop_constraint('stock_movements_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stock_movements_product_id_fkey', 'products', ['product_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_stock_movements_variant_id'))
        batch_op.create_index('ix_stock_movements_product_id', ['product_id'], unique=False)
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sale_items_product_id_fkey', 'products', ['product_id'], ['id'])
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_products_barcode', ['barcode'], unique=True)
        batch_op.drop_column('brand_id')
        batch_op.drop_column('category_id')

    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='inventory_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventory_pkey'),
    sa.UniqueConstraint('product_id', name='inventory_product_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('product_variants')
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sizes_name'))

    op.drop_table('sizes')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_name'))

    op.drop_table('brands')
    # ### end Alembic commands ###
